# SPDX-License-Identifier: Apache-2.0
"""Aurekai Python SDK — bridge for the Aurekai Native Runtime."""

__version__ = "0.8.0a2"

OPERATORS = {
    "api": {"binary": "BonfyreAPI", "category": "platform", "description": "BonfyreAPI v2 \u2014 Async HTTP gateway for the Bonfyre binary family"},
    "auth": {"binary": "BonfyreAuth", "category": "platform", "description": "BonfyreAuth \u2014 user management and session tokens"},
    "brief": {"binary": "BonfyreBrief", "category": "artifacts", "description": "preserve document order */"},
    "canon": {"binary": "BonfyreCanon", "category": "data", "description": "BonfyreCanon \u2014 structure-aware canonicalization via Tree-sitter"},
    "capability": {"binary": "BonfyreCapability", "category": "platform", "description": "bonfyre-capability - capability discovery and matching layer"},
    "cli": {"binary": "BonfyreCLI", "category": "platform", "description": "bonfyre \u2014 unified CLI dispatcher"},
    "clips": {"binary": "BonfyreClips", "category": "media", "description": "BonfyreClips \u2014 Clip Discovery Engine"},
    "cms": {"binary": "BonfyreCMS", "category": "data", "description": "BonfyreCMS \u2014 stripped binary CMS"},
    "compete": {"binary": "BonfyreCompete", "category": "specialized", "description": "bonfyre-compete \u2014 stage/model A/B competition engine"},
    "compress": {"binary": "BonfyreCompress", "category": "data", "description": "BonfyreCompress \u2014 family-aware compression engine"},
    "control": {"binary": "BonfyreControl", "category": "misc", "description": "bonfyre-control \u2014 control plane for Bonfyre inference pipelines"},
    "detect-objects": {"binary": "BonfyreDetectObjects", "category": "specialized", "description": "BonfyreDetectObjects \u2014 Object detection operator for V1/I1 pipelines"},
    "discip": {"binary": "BonfyreDiscipl", "category": "specialized", "description": "BonfyreDiscipl operator"},
    "distribute": {"binary": "BonfyreDistribute", "category": "artifacts", "description": "BonfyreDistribute operator"},
    "economy": {"binary": "BonfyreEconomy", "category": "specialized", "description": "bonfyre-economy \u2014 cost-aware routing and budget enforcement"},
    "embed": {"binary": "BonfyreEmbed", "category": "inference", "description": "BonfyreEmbed \u2014 text embeddings via ONNX Runtime C API"},
    "emit": {"binary": "BonfyreEmit", "category": "artifacts", "description": "BonfyreEmit \u2014 multi-format output engine"},
    "entity": {"binary": "BonfyreEntity", "category": "knowledge", "description": "bonfyre-entity \u2014 universal identity resolution layer"},
    "family": {"binary": "BonfyreFamily", "category": "specialized", "description": "bonfyre-family - conceptual family browser for Bonfyre"},
    "finance": {"binary": "BonfyreFinance", "category": "data", "description": "BonfyreFinance \u2014 service arbitrage, labor pipeline, and bundle pricing engine"},
    "flash-qla": {"binary": "BonfyreFlashQLA", "category": "inference", "description": "bonfyre-flashqla \u2014 BonfyreGDN Chunked Prefill (native C kernel)"},
    "flow": {"binary": "BonfyreFlow", "category": "pipeline", "description": "bonfyre-flow \u2014 coroutine-native pipeline programming"},
    "fpq": {"binary": "BonfyreFPQ", "category": "inference", "description": "main.c \u2014 bonfyre-fpq CLI"},
    "fpqx": {"binary": "BonfyreFPQx", "category": "inference", "description": "bonfyre-fpqx \u2014 Cross-family FPQ alignment"},
    "fragment": {"binary": "BonfyreFragment", "category": "knowledge", "description": "BonfyreFragment \u2014 Fragment system CLI"},
    "frame-extract": {"binary": "BonfyreFrameExtract", "category": "media", "description": "bonfyre-frame-extract"},
    "gate": {"binary": "BonfyreGate", "category": "pipeline", "description": "BonfyreGate \u2014 license enforcement + access control"},
    "gen": {"binary": "BonfyreGen", "category": "data", "description": "bonfyre-gen \u2014 natural language \u2192 recipe YAML generator"},
    "graph": {"binary": "BonfyreGraph", "category": "knowledge", "description": "BonfyreGraph \u2014 Merkle-DAG artifact graph engine"},
    "hash": {"binary": "BonfyreHash", "category": "artifacts", "description": "BonfyreHash \u2014 content-addressing + Merkle DAG hashing engine"},
    "index": {"binary": "BonfyreIndex", "category": "knowledge", "description": "BonfyreIndex \u2014 artifact family indexer and search engine"},
    "ingest": {"binary": "BonfyreIngest", "category": "artifacts", "description": "BonfyreIngest \u2014 universal intake binary"},
    "kv-cache": {"binary": "BonfyreKVCache", "category": "knowledge", "description": "bonfyre-kvcache \u2014 v8 RLF KV cache compression"},
    "layer": {"binary": "BonfyreLayer", "category": "knowledge", "description": "bonfyre-layer \u2014 Layer-aware ONNX model inspection and extraction (C port)"},
    "leapfrog": {"binary": "BonfyreLeapfrog", "category": "inference", "description": "bonfyre-leapfrog \u2014 Hamiltonian conservation and reversibility test"},
    "learn": {"binary": "BonfyreLearn", "category": "inference", "description": "bonfyre-learn \u2014 artifact-level feedback and threshold tuning"},
    "ledger": {"binary": "BonfyreLedger", "category": "artifacts", "description": "BonfyreLedger \u2014 value accounting engine"},
    "media-prep": {"binary": "BonfyreMediaPrep", "category": "media", "description": "BonfyreMediaPrep operator"},
    "meter": {"binary": "BonfyreMeter", "category": "platform", "description": "BonfyreMeter \u2014 usage metering + billing events"},
    "mfa-dict": {"binary": "BonfyreMFADict", "category": "specialized", "description": "BonfyreMFADict operator"},
    "model": {"binary": "BonfyreModel", "category": "inference", "description": "BonfyreModel \u2014 model dependency manager for bonfyre pipelines"},
    "moq": {"binary": "BonfyreMoQ", "category": "specialized", "description": "bonfyre-moq \u2014 Media over QUIC style relay for Bonfyre"},
    "narrate": {"binary": "BonfyreNarrate", "category": "media", "description": "BonfyreNarrate v3 \u2014 Verified Tone-Aware Text-to-Speech Synthesis"},
    "net": {"binary": "BonfyreNet", "category": "platform", "description": "bonfyre-net \u2014 Bonfyre Netlist Runtime"},
    "offer": {"binary": "BonfyreOffer", "category": "artifacts", "description": "Also try to read proof-summary.json from"},
    "orchestrate": {"binary": "BonfyreOrchestrate", "category": "pipeline", "description": "BonfyreOrchestrate operator"},
    "outreach": {"binary": "BonfyreOutreach", "category": "data", "description": "BonfyreOutreach \u2014 quiet distribution engine"},
    "pack": {"binary": "BonfyrePack", "category": "artifacts", "description": "BonfyrePack operator"},
    "paragraph": {"binary": "BonfyreParagraph", "category": "knowledge", "description": "BonfyreParagraph operator"},
    "pay": {"binary": "BonfyrePay", "category": "data", "description": "BonfyrePay \u2014 payment & invoice management"},
    "physics": {"binary": "BonfyrePhysics", "category": "inference", "description": "bonfyre-physics \u2014 Hamiltonian Version Control Protocol (HVCP) CLI"},
    "pipeline": {"binary": "BonfyrePipeline", "category": "pipeline", "description": "BonfyrePipeline \u2014 unified single-process pipeline"},
    "project": {"binary": "BonfyreProject", "category": "data", "description": "BonfyreProject operator"},
    "proof": {"binary": "BonfyreProof", "category": "artifacts", "description": "BonfyreProof operator"},
    "proxy": {"binary": "BonfyreProxy", "category": "platform", "description": "BonfyreProxy \u2014 OpenAI-compatible API shim for Bonfyre binaries"},
    "quant": {"binary": "BonfyreQuant", "category": "data", "description": "bonfyre-quant \u2014 FPQ v8 Recursive Lattice-Flow weight quantization"},
    "query": {"binary": "BonfyreQuery", "category": "knowledge", "description": "BonfyreQuery \u2014 local analytics engine over artifacts via DuckDB"},
    "queue": {"binary": "BonfyreQueue", "category": "pipeline", "description": "BonfyreQueue v2 \u2014 SQLite-backed job queue with built-in worker daemon"},
    "reason": {"binary": "BonfyreReason", "category": "specialized", "description": "bonfyre-reason \u2014 Reason-state operator over the HVCP stack"},
    "recipe": {"binary": "BonfyreRecipe", "category": "pipeline", "description": "BonfyreRecipe \u2014 Recipe Registry Management"},
    "render": {"binary": "BonfyreRender", "category": "artifacts", "description": "BonfyreRender operator"},
    "repurpose": {"binary": "BonfyreRepurpose", "category": "media", "description": "BonfyreRepurpose \u2014 Transform brief artifacts into social media formats"},
    "run": {"binary": "BonfyreRun", "category": "pipeline", "description": "BonfyreRun \u2014 Recipe Executor"},
    "runtime": {"binary": "BonfyreRuntime", "category": "platform", "description": "Try top-level sibling path: ../SiblingDir/binary */"},
    "sae": {"binary": "BonfyreSAE", "category": "inference", "description": "bonfyre-sae \u2014 SAE feature dictionary runtime"},
    "scene-detect": {"binary": "BonfyreSceneDetect", "category": "media", "description": "bonfyre-scene-detect"},
    "segment": {"binary": "BonfyreSegment", "category": "specialized", "description": "BonfyreSegment \u2014 Idea Boundary Detection + Segment Graph"},
    "sli": {"binary": "BonfyreSLI", "category": "inference", "description": "bonfyre-sli \u2014 Structured Layer Inference"},
    "space": {"binary": "BonfyreSpace", "category": "knowledge", "description": "bonfyre-space \u2014 shared memory substrate"},
    "speech-loop": {"binary": "BonfyreSpeechLoop", "category": "media", "description": "BonfyreSpeechLoop \u2014 Whisper \u2192 Transform \u2192 Piper speech transformation"},
    "stitch": {"binary": "BonfyreStitch", "category": "media", "description": "BonfyreStitch \u2014 DAG materializer"},
    "surface": {"binary": "BonfyreSurface", "category": "specialized", "description": "BonfyreSurface operator"},
    "swarm": {"binary": "BonfyreSwarm", "category": "pipeline", "description": "BonfyreSwarm \u2014 P2P artifact distribution via BitTorrent v2 protocol"},
    "sync": {"binary": "BonfyreSync", "category": "artifacts", "description": "BonfyreSync operator"},
    "tag": {"binary": "BonfyreTag", "category": "knowledge", "description": "BonfyreTag \u2014 instant intent/topic tagging via fastText (pure C)"},
    "tel": {"binary": "BonfyreTel", "category": "platform", "description": "BonfyreTel \u2014 FreeSWITCH Event Socket telephony adapter"},
    "tier": {"binary": "BonfyreTier", "category": "data", "description": "bonfyre-tier \u2014 latency tier management and SLA enforcement"},
    "time": {"binary": "BonfyreTime", "category": "data", "description": "bonfyre-time \u2014 temporal pipeline manager"},
    "tone": {"binary": "BonfyreTone", "category": "media", "description": "BonfyreTone \u2014 speech tone/emotion/rhythm extraction via OpenSMILE"},
    "transcribe": {"binary": "BonfyreTranscribe", "category": "media", "description": "================================================================"},
    "transcript-clean": {"binary": "BonfyreTranscriptClean", "category": "specialized", "description": "BonfyreTranscriptClean operator"},
    "transcript-family": {"binary": "BonfyreTranscriptFamily", "category": "specialized", "description": "BonfyreTranscriptFamily operator"},
    "vec": {"binary": "BonfyreVec", "category": "knowledge", "description": "BonfyreVec \u2014 local vector search via sqlite-vec"},
    "video-demux": {"binary": "BonfyreVideoDemux", "category": "media", "description": "bonfyre-video-demux"},
    "violence": {"binary": "BonfyreViolence", "category": "specialized", "description": "bonfyre-violence \u2014 real coupling test harness"},
    "watch": {"binary": "BonfyreWatch", "category": "platform", "description": "BonfyreWatch operator"},
    "weaviate-index": {"binary": "BonfyreWeaviateIndex", "category": "specialized", "description": "BonfyreWeaviateIndex operator"},
    "wire": {"binary": "BonfyreWire", "category": "platform", "description": "BonfyreWire operator"},
    "workflow": {"binary": "BonfyreWorkflow", "category": "pipeline", "description": "bonfyre-workflow - workflow profile browser"},
}
